name: Build Base docker image 
on: workflow_dispatch

jobs:
  Dependency_Build:
    name: Base docker image
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: pre-build 3rdParty libs 
        run: |
          echo "=== Build start ==="
          echo 717lumos | sudo -S echo ""         
          cd dockerfiles
          echo "=== Log Docker image status ==="
          sudo docker images 
          echo "=== Temporary Docker image build start ==="              
          sudo docker build --force-rm --no-cache -t proslam:base_temp . -f base.dockerfile
          echo "=== Temporary Docker image build finished ==="
          echo "=== Log Docker image status ==="
          echo 717lumos | sudo -S echo ""
          sudo docker images
          echo "=== Replace old Docker image with temporary image start ==="
          sudo docker rmi proslam:base
          sudo docker image tag slam:base_temp proslam:base
          sudo docker rmi proslam:base_temp
          sudo docker images 
          echo "=== Job finished ===" 

      - name: Clean up Docker image if build fails
        run: |
          echo "=== Clean up start ==="  
          echo 717lumos | sudo -S echo "" 
          echo "=== Log Docker image status ==="
          sudo docker images 
          sudo docker rmi -f $(sudo docker images -f "dangling=true" -q)
          echo "=== Delete dangling Docker images ===" 
          echo "=== Log Docker image status ==="
          sudo docker images
          echo "=== Clean up finished ==="
        if: failure()
